### ISSUE TITLE
Map load errors

### ISSUE THREAD

**Issue by ShawnPR1** [walrusone/SkyWarsReloaded#62] opened 2018-04-24 13:56 UTC
I have never seen such an amazing plugin before in terms of minigames. It's really well set up in terms of teleporting players to lobby, giving them items in their inventory for mini-game interaction, etc.

I must, however, say that I've run into a critical bug. I created a map and pasted a schematic in (at 0, 70, 0). Added all the spawn points, registered it and then got teleported to the lobby. Perfect! Problem is, upon joining the map, most of it is missing.

I made some changes to the spawns, rejoined the map, and the whole damn map was gone. What is going on?

**Comment by MineBlo** [comment] 2018-09-22 08:21
Same Pls Fix it

**Comment by lukasvdgaag** [comment] 2018-10-31 18:48
Okay, this is a bug that comes up to people a LOT, but luckily for you guys: I fixed it.
Somehow the map bugs when you create it somewhere around (0,70,0), the cause is unknown. But the solution is easy: Do not create it 'round that location! Fly away REALLY, REALLY far from the center (0,70,0) and create/paste it there.
If you want more information about this bug, take a look here: https://www.spigotmc.org/wiki/skywarsreloaded-help/#my-map-is-incomplete-missing-blocks-map-load-errors

**Comment by walrusone** [comment] 2019-01-31 17:56
This will be fixed in the next release that I'm currently working on. It took me forever to find the actual issue and find a fix. I'll be syncing a 1.13.2 version later today, but it may be a week or more before I push the release to spigot so that I can complete more testing.

**Closed as completed by walrusone** 2019-01-31 17:56 UTC
