### ISSUE TITLE
AsyncPlayerChatEvent to Skywars

### ISSUE THREAD

**Issue by AIphaDragon** [walrusone/SkyWarsReloaded#67] opened 2018-05-09 07:41 UTC
Hello! Found an error when sending messages. We use essential. Thanks in advance for your help.
Error: https://pastebin.com/z8dFaut2

**Comment by Superdarco** [comment] 2018-05-20 18:49
Yea, me too in 1.8:
[19:47:46] [Async Chat Thread - #1/ERROR]: Could not pass event AsyncPlayerChatEvent to Skywars v3.4.2-Snapshot
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot_1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot_1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot_1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [Spigot_1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1084) [Spigot_1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1022) [Spigot_1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [Spigot_1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
	at com.walrusone.skywarsreloaded.listeners.ChatListener.onChat(ChatListener.java:184) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot_1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	... 11 more

**Comment by lukasvdgaag** [comment] 2018-10-31 18:33
Okay, it may be a little bit late ;)
But here is the solution to your problem:

Your config.yml is missing, your spawnpoint is invalid OR your spawnpoint hasn't been set. 
Restart the server/plugin, set your spawnpoint again or set your spawnpoint.
If you want more information about the cause look here: https://www.spigotmc.org/wiki/skywarsreloaded-help/#i-get-errors-when-i-chat-asyncplayerchatevent-error

**Comment by walrusone** [comment] 2019-01-31 18:16
Should be fixed now.

**Closed as completed** 2019-01-31 18:16 UTC
